# Generated by Django 2.1.3 on 2018-11-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caracole', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accueil',
            old_name='body',
            new_name='content',
        ),
    ]
