# Generated by Django 3.1.7 on 2021-04-01 01:10

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("caracole", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accueil",
            name="permanences",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="permanences"
            ),
        ),
    ]
