# Generated by Django 4.1.7 on 2023-03-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caracole", "0003_alter_amis_id_alter_blogtag_id_alter_blogtag_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="img_caption",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="légende de l`image"
            ),
        ),
        migrations.AlterField(
            model_name="carapage",
            name="citation",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="auteur de l`exergue",
            ),
        ),
        migrations.AlterField(
            model_name="carapage",
            name="img_caption",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="légende de l`image"
            ),
        ),
    ]
