# Generated by Django 2.1.3 on 2018-11-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracole', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caramel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mail', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
