# Generated by Django 2.1.3 on 2018-11-19 13:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('caracole', '0005_caramel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('horaires', models.CharField(max_length=200)),
                ('lieu', models.CharField(max_length=200)),
                ('caracole', models.BooleanField(default=True, verbose_name='évènement de caracole')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evenements',
            fields=[
                ('carapage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='caracole.CaraPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('caracole.carapage',),
        ),
        migrations.AddField(
            model_name='evenement',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenement', to='caracole.CaraPage'),
        ),
    ]
