# Generated by Django 2.1.3 on 2018-11-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracole', '0006_evenements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='description',
            field=models.CharField(max_length=95),
        ),
    ]
