# Generated by Django 2.1.3 on 2018-11-19 15:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('caracole', '0007_auto_20181119_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenements',
            name='zoom_description',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evenements',
            name='zoom_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='evenements',
            name='zoom_titre',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
