version: '3'

volumes:
  srv:
  sql:

services:
  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "sql:/var/lib/postgresql/data"
  memcached:
    image: memcached:alpine
    restart: unless-stopped
  app:
    image: caracole/caracole.io
    build: .
    restart: unless-stopped
    volumes:
      - "srv:/srv"
    env_file:
      - .env
    environment:
      - DB=postgres
      - MEMCACHED=True
      - RAVEN=True
    networks:
      - proxytanet
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host: caracole.${DOMAIN_NAME:-io}, www.caracole.${DOMAIN_NAME:-io}, caracole.totheweb.fr"
      - "traefik.frontend.redirect.regex=^https://caracole.totheweb.fr/(.*)"
      - "traefik.frontend.redirect.replacement=https://caracole.io/$$1"
      - "traefik.docker.network=proxytanet"
  nginx:
    image: nim65s/ndh:nginx
    restart: unless-stopped
    volumes:
      - "srv:/srv"
    networks:
      - proxytanet
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host: caracole.${DOMAIN_NAME:-io}; PathPrefix: /static, /media"

networks:
  proxytanet:
    external: true
