version: '3'

services:
  postgres:
    image: postgres:11-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "${CHATONS_ROOT_DIR:-/srv/chatons}/caracole.io/sql:/var/lib/postgresql/data"
  app:
    image: caracole/caracole.io
    build: .
    restart: unless-stopped
    volumes:
      - "${CHATONS_ROOT_DIR:-/srv/chatons}/caracole.io/srv:/srv"
    env_file:
      - .env
    environment:
      - DB=postgres
      - MEMCACHED=True
      - RAVEN=False
    networks:
      - web
      - default
    labels:
      traefik.enable: "true"
      traefik.http.routers.caracole-app.rule: "Host(`caracole.${DOMAIN_NAME:-io}`, `www.caracole.${DOMAIN_NAME:-io}`)"
  nginx:
    image: nim65s/ndh:nginx
    restart: unless-stopped
    volumes:
      - "${CHATONS_ROOT_DIR:-/srv/chatons}/caracole.io/srv/caracole:/srv:ro"
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.http.routers.caracole-ngx.rule: "Host(`caracole.${DOMAIN_NAME:-io}`, `www.caracole.${DOMAIN_NAME:-io}`) && PathPrefix(`/static`, `/media`)"

networks:
  web:
    external: true
