# Generated by Django 2.1.3 on 2018-11-13 00:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0021_image_file_hash'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaraPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('nom', models.CharField(max_length=250)),
                ('img_caption', models.CharField(blank=True, max_length=250, null=True, verbose_name='légende de l’image')),
                ('exergue', models.TextField(blank=True, null=True)),
                ('citation', models.CharField(blank=True, max_length=250, null=True, verbose_name='auteur de l’exergue')),
                ('content', wagtail.core.fields.RichTextField(blank=True, verbose_name='contenu')),
                ('img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=250, verbose_name='titre')),
                ('content', wagtail.core.fields.RichTextField(blank=True, verbose_name='contenu')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubriques', to='pages.CaraPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
