# Generated by Django 2.1.3 on 2018-11-13 13:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('pages', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=250, verbose_name='titre')),
                ('href', models.URLField(blank=True, null=True, verbose_name='lien')),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Liens',
            fields=[
                ('carapage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.CaraPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.carapage',),
        ),
        migrations.AddField(
            model_name='amis',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='amis', to='pages.CaraPage'),
        ),
    ]
